//! Fluent-based i18n for log messages and RPC replies.
//!
//! FTL lang files are bundled at compile time via `build.rs` (`BUNDLED_LANGS`).
//! A compiled-in `i18n_cid` from `src/i18n.yaml` (generated by `make src/i18n.yaml`)
//! is used as the default IPFS lang-map pointer; `config.extra["i18n_cid"]` overrides it.
//! Call [`init`] once after Kubo is ready.

use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};

use fluent::{FluentBundle, FluentResource};
use unic_langid::LanguageIdentifier;

use crate::entity::{IpldLink, RuntimeManifest};
use crate::kubo;

/// All messages keyed by `(lang_code, message_id)`. Wrapped in `RwLock` so
/// the runtime language can be switched at any time without restart.
static MESSAGES: OnceLock<RwLock<HashMap<String, HashMap<String, String>>>> = OnceLock::new();
static RUNTIME_LANG: OnceLock<RwLock<String>> = OnceLock::new();

// `BUNDLED_LANGS` is auto-generated by build.rs from all `lang/*.ftl` files.
// Drop a new FTL file and rebuild — it is included automatically.
include!(concat!(env!("OUT_DIR"), "/bundled_langs.rs"));

/// Compiled-in `src/i18n.yaml` — generated by `make src/i18n.yaml`.
/// Contains `i18n_cid` (the IPFS DAG-CBOR map CID) and per-language CIDs.
const LANG_YAML: &str = include_str!("i18n.yaml");

/// Returns the compiled-in fallback lang-map CID from `src/i18n.yaml`.
/// `None` when `make src/i18n.yaml` has never been run.
pub fn default_lang_cid() -> Option<&'static str> {
    static CID: OnceLock<Option<String>> = OnceLock::new();
    CID.get_or_init(|| {
        let v: serde_yaml::Value = serde_yaml::from_str(LANG_YAML).ok()?;
        v.get("i18n_cid")?.as_str().map(String::from)
    })
    .as_deref()
}

/// Per-language CIDs from the compiled-in `src/i18n.yaml`.
/// Returns an empty map when `make src/i18n.yaml` has never been run.
pub fn bundled_lang_map() -> HashMap<String, IpldLink> {
    let v: serde_yaml::Value = serde_yaml::from_str(LANG_YAML).unwrap_or_default();
    let langs = v
        .get("langs")
        .and_then(|l| l.as_mapping())
        .cloned()
        .unwrap_or_default();
    langs
        .into_iter()
        .filter_map(|(k, v)| {
            k.as_str()
                .zip(v.as_str())
                .map(|(k, cid)| (k.to_string(), IpldLink::new(cid)))
        })
        .collect()
}

/// All known message IDs — must match keys in both FTL files.
const MESSAGE_IDS: &[&str] = &[
    // Startup / shutdown
    "own-did-published",
    "own-did-publish-failed",
    "own-did-publish-timeout",
    "started",
    "shutdown-requested",
    "closing-endpoint",
    "shutdown-complete",
    // Infrastructure
    "status-listening",
    "rpc-message-received",
    "rpc-message-rejected",
    "ipfs-message-rejected",
    "ctrlc-handler-failed",
    "node-connected",
    "received-encrypted-ma-msg",
    // RPC
    "unknown-rpc-atom",
    "rpc-reply-sent",
    "ping-received",
    // IPFS publisher
    "did-publish-request-received",
    "document-published",
    "did-publish-cid-reply-sent",
    "did-publish-resolve-failed",
    "ipfs-store-request-received",
    "ipfs-stored",
    "ipfs-store-cid-reply-sent",
    "ipfs-store-resolve-failed",
    // Entity dispatch
    "bootstrap-complete",
    "entity-loaded",
    "entity-load-failed",
    "entity-not-found",
    "entity-dispatched",
    "entity-replied",
    "root-create-entity",
    "root-list-entities",
    "root-delete-entity",
    "root-entity-updated",
    "default-config-root-populated",
    "default-config-root-no-root-entity",
    "default-config-root-no-root-cid",
    "default-config-root-inspect-failed",
    "default-config-root-populate-failed",
    "entity-created",
    "entity-reloaded",
    "entity-reload-skipped",
    "entity-reload-started",
    "entity-reload-kind-lookup-failed",
    "entity-reload-kind-missing",
    "entity-reload-kind-fetch-failed",
    "entity-reload-kind-extends-failed",
    "entity-reload-manifest-state-update-failed",
    "entity-reload-state-persist-failed",
    "entity-reload-current-node-load-failed",
    "entity-reload-failed",
    "entity-reload-state-produced-failed",
    "entity-reloaded-manifest-updated",
    "entity-reloaded-manifest-update-failed",
    "bootstrap-remote-root-pin-misconfigured",
    "bootstrap-remote-root-pin-confirmed",
    "bootstrap-kinds-tree-published",
    "bootstrap-kinds-overlay-pin-update-failed",
    "bootstrap-kinds-overlay-published",
    "bootstrap-runtime-manifest-published",
    "bootstrap-root-pin-replacement-failed",
    "bootstrap-root-pin-update-failed",
    "bootstrap-kind-published",
    "bootstrap-entity-registering-prepublished",
    "bootstrap-entity-published",
    "bootstrap-acl-published",
    "bootstrap-group-published",
    "bootstrap-root-acl-published",
    "bootstrap-kind-registry-hydrated",
    "bootstrap-lifecycle-manifest-pin-update-failed",
    "bootstrap-lifecycle-manifest-published",
    "bootstrap-lifecycle-manifest-publish-failed",
    "bootstrap-entity-lifecycle-updated",
    "bootstrap-entity-lifecycle-update-failed",
    "bootstrap-entity-node-shutdown-updated",
    "bootstrap-entity-registry-not-in-manifest",
    "plugin-outbox-drain-limit",
    "plugin-outbox-congested",
    "plugin-envelope-local-reply-dropped",
    "plugin-envelope-local-gate-closed",
    "plugin-envelope-local-timeout",
    "plugin-envelope-recipient-invalid",
    "plugin-envelope-build-failed",
    "plugin-envelope-remote-limit",
    "scheduled-dispatch-error",
    "scheduled-dispatch-manifest-writer-unavailable",
    "manifest-pin-update-failed",
    "bootstrap-kind-registry-fetch-log-failed",
    "bootstrap-entity-state-update-fetch-failed",
    "schedule-stale-dispatch-skipped",
    "schedule-random-reschedule-failed",
    "schedule-random-create-failed",
    "schedule-random-chain-stopped",
    "schedule-entity-not-found",
    "schedule-dispatch-firing",
    "bootstrap-kind-registry-fetch-failed",
    "bootstrap-kind-registry-extends-failed",
    "bootstrap-entity-registry-fetch-failed",
    "bootstrap-entity-registry-kind-missing",
    "bootstrap-entity-registry-kind-fetch-failed",
    "bootstrap-entity-registry-kind-extends-failed",
    "bootstrap-manifest-fetch-failed",
    "bootstrap-minimal-manifest-failed",
    "bootstrap-entity-state-save-failed",
    "bootstrap-entity-state-shutdown-aborted",
    "bootstrap-root-cid-shutdown-persist-failed",
    "bootstrap-root-cid-shutdown-publish-succeeded",
    "bootstrap-root-cid-shutdown-publish-failed",
    "bootstrap-root-cid-shutdown-publish-timeout",
    "bootstrap-endpoint-close-timeout",
    "bootstrap-endpoint-close-stuck",
    "bootstrap-envelope-delivery-failed",
    "bootstrap-envelope-open-failed",
    "boot-minimal-manifest-not-found",
    "boot-minimal-manifest-bootstrapped",
    "boot-kinds-overlay-no-change",
    "boot-kinds-overlay-applied",
    "boot-load-manifest-for-acl-cache-failed",
    "boot-root-acl-loaded-from-manifest",
    "boot-root-acl-load-failed",
    "boot-group-loaded-into-cache",
    "boot-group-load-failed",
    "boot-root-acl-loaded-into-cache",
    "boot-root-acl-load-cache-failed",
    "boot-reconciled-owners-persist-failed",
    "boot-reconciled-owners-published",
    "boot-reconciled-owners-manifest-failed",
    "boot-no-root-entity",
    "boot-default-root-config-populated",
    "boot-default-root-config-populate-failed",
    "boot-default-root-config-skip",
    "boot-entity-load-processed",
    "boot-runtime-kinds-overlay-failed",
    "boot-runtime-manifest-load-failed",
    "boot-runtime-root-cid-resolve-failed",
    "inbox-empty-payload-dropped",
    "inbox-unfragmented-dropped",
    "inbox-unknown-entity",
    "inbox-dispatching",
    "inbox-behaviour-ignored",
    "plugin-envelope-local-recipient-unknown",
    "plugin-envelope-local-dispatch-start",
    "plugin-envelope-local-dispatch-finish",
    "plugin-envelope-local-dispatch-failed",
    "plugin-envelope-create-requests-ignored",
    "ma-create-entity-already-exists",
    "ma-create-entity-kind-missing",
    "ma-create-entity-invalid-behaviour",
    "plugin-dispatch-rejected",
    "crud-message-rejected",
    "inbox-message-rejected",
    "outbox-connect-failed-fallback",
    "outbox-connect-timed-out-fallback",
    "outbox-connect-backoff",
    "outbox-connect-timeout-backoff",
    "entity-deleted",
    "entity-states-saving",
    "entity-state-saving",
    "entity-state-saved",
    "entity-state-empty",
    "entity-states-saved",
    // i18n itself
    "ftl-loaded",
    // First-run auto-init
    "no-config-found",
    "initialising-new-identity",
    "generated-headless-config",
    // Ownership / claim
    "runtime-claimed",
    "runtime-claim-persisted",
    "runtime-already-claimed",
    // ACL
    "acl-owners-access",
    // CRUD infrastructure
    "crud-message-received",
    "crud-acl-updated",
    // Client-facing CRUD / RPC error replies
    "refuse-delete-root",
    "no-root-acl",
    "rpc-not-text-atom",
    "rpc-unknown-verb",
    // Client-facing CRUD validation errors
    "blob-value-ipfs-path",
    "acl-value-ipfs-path",
    "kind-value-ipfs-path",
    "config-key-protected",
    "config-key-no-delete",
    "config-key-not-manifest",
    "wrong-crud-protocol",
];

/// Initialise i18n by loading all compiled-in FTL bundles and fetching any
/// additional ones from IPFS. `lang` is the runtime's own language.
///
/// On first call the `RwLock` statics are created. On subsequent calls
/// messages and the active language are updated through the write locks, so
/// the runtime is immediately re-localised without restarting.
pub async fn init(lang: &str, kubo_url: &str, lang_cid: Option<&str>, root_cid: Option<&str>) {
    let messages = load_all_messages(kubo_url, lang_cid, root_cid).await;
    if MESSAGES.set(RwLock::new(messages.clone())).is_err() {
        if let Some(lock) = MESSAGES.get() {
            *lock.write().expect("MESSAGES poisoned") = messages;
        }
    }
    if RUNTIME_LANG.set(RwLock::new(lang.to_string())).is_err() {
        if let Some(lock) = RUNTIME_LANG.get() {
            *lock.write().expect("RUNTIME_LANG poisoned") = lang.to_string();
        }
    }
}

/// Return the localised string for `id` in the runtime's own language.
/// Falls back to `id` itself when [`init`] has not been called or the key is
/// unknown — so callers always get *something* human-readable.
#[must_use]
pub fn t(id: &str) -> String {
    let lang = runtime_lang();
    t_lang(&lang, id)
}

/// Like [`t_lang`] but substitutes `%name%` placeholders in the translated
/// string with caller-supplied values.  Placeholders use `%name%` syntax
/// (not Fluent `{ $name }`) so the FTL values remain plain text.
#[must_use]
pub fn tf_lang(lang: &str, id: &str, args: &[(&str, &str)]) -> String {
    let mut s = t_lang(lang, id);
    for (name, value) in args {
        s = s.replace(&format!("%{name}%"), value);
    }
    s
}

/// Return the localised string for `id` in `lang`.
/// Falls back to "en" if `lang` is not loaded, then to the key name.
#[must_use]
pub fn t_lang(lang: &str, id: &str) -> String {
    let Some(lock) = MESSAGES.get() else {
        return id.to_string();
    };
    let Ok(all) = lock.read() else {
        return id.to_string();
    };
    all.get(lang)
        .or_else(|| all.get("en"))
        .and_then(|m| m.get(id))
        .cloned()
        .unwrap_or_else(|| id.to_string())
}

/// The runtime's own language code (set by [`init`]; defaults to "en").
#[must_use]
pub fn runtime_lang() -> String {
    RUNTIME_LANG
        .get()
        .and_then(|lock| lock.read().ok().map(|g| g.clone()))
        .unwrap_or_else(|| "en".to_string())
}

/// Returns `true` if messages for `lang` have been loaded.
#[must_use]
pub fn has_lang(lang: &str) -> bool {
    MESSAGES
        .get()
        .and_then(|lock| lock.read().ok().map(|all| all.contains_key(lang)))
        .unwrap_or(false)
}

/// Switch the runtime language immediately without restarting.
///
/// Tries the compiled-in FTL bundle first (no network needed). Falls back to
/// fetching the raw FTL blob from IPFS via the CID in `src/i18n.yaml`.
/// No-op when the language is unknown and unreachable from IPFS.
pub async fn switch_lang(lang: &str, kubo_url: &str) {
    let messages = if let Some((_, ftl)) = BUNDLED_LANGS.iter().find(|(code, _)| *code == lang) {
        parse_ftl(ftl, lang)
    } else {
        let lang_map = bundled_lang_map();
        let Some(link) = lang_map.get(lang) else {
            return;
        };
        let Ok(bytes) = kubo::cat_bytes(kubo_url, &link.cid).await else {
            return;
        };
        let Ok(ftl) = String::from_utf8(bytes) else {
            return;
        };
        parse_ftl(&ftl, lang)
    };
    if let Some(lock) = MESSAGES.get() {
        lock.write()
            .expect("MESSAGES poisoned")
            .insert(lang.to_string(), messages);
    }
    if let Some(lock) = RUNTIME_LANG.get() {
        *lock.write().expect("RUNTIME_LANG poisoned") = lang.to_string();
    }
}

// ── Internals ─────────────────────────────────────────────────────────────────

fn parse_ftl(ftl: &str, lang: &str) -> HashMap<String, String> {
    let Ok(resource) = FluentResource::try_new(ftl.to_string()) else {
        return key_name_fallback();
    };
    let langid: LanguageIdentifier = lang
        .parse()
        .unwrap_or_else(|_| "en".parse().expect("invalid fallback lang"));
    let mut bundle: FluentBundle<FluentResource> = FluentBundle::new(vec![langid]);
    if bundle.add_resource(resource).is_err() {
        return key_name_fallback();
    }

    let mut map = HashMap::new();
    for &id in MESSAGE_IDS {
        if let Some(msg) = bundle.get_message(id) {
            if let Some(pattern) = msg.value() {
                let mut errors = vec![];
                let value = bundle.format_pattern(pattern, None, &mut errors);
                map.insert(id.to_string(), value.into_owned());
            } else {
                map.insert(id.to_string(), id.to_string());
            }
        } else {
            map.insert(id.to_string(), id.to_string());
        }
    }
    map
}

fn key_name_fallback() -> HashMap<String, String> {
    MESSAGE_IDS
        .iter()
        .map(|&id| (id.to_string(), id.to_string()))
        .collect()
}

#[test]
fn entity_reload_log_keys_are_in_english_catalogue() {
    let all_messages = bundled_messages();
    let en_messages = all_messages
        .get("en")
        .expect("bundled English FTL catalogue should exist");

    for key in [
        "entity-reload-skipped",
        "entity-reload-started",
        "entity-reload-kind-lookup-failed",
        "entity-reload-kind-missing",
        "entity-reload-kind-fetch-failed",
        "entity-reload-kind-extends-failed",
        "entity-reload-manifest-state-update-failed",
        "entity-reload-state-persist-failed",
        "entity-reload-current-node-load-failed",
        "entity-reload-failed",
        "entity-reload-state-produced-failed",
        "entity-reloaded-manifest-updated",
        "entity-reloaded-manifest-update-failed",
    ] {
        let value = en_messages.get(key).expect("missing english FTL key");
        assert_ne!(value.as_str(), key, "missing english FTL entry for {key}");
    }
}

fn bundled_messages() -> HashMap<String, HashMap<String, String>> {
    BUNDLED_LANGS
        .iter()
        .map(|&(code, ftl)| (code.to_string(), parse_ftl(ftl, code)))
        .collect()
}

async fn fetch_lang_map(
    kubo_url: &str,
    lang_cid: Option<&str>,
    root_cid: Option<&str>,
) -> HashMap<String, IpldLink> {
    if let Some(cid) = lang_cid {
        if let Ok(map) = kubo::dag_get(kubo_url, cid).await {
            return map;
        }
    }
    if let Some(cid) = root_cid {
        if let Ok(manifest) = kubo::dag_get::<RuntimeManifest>(kubo_url, cid).await {
            return manifest.i18n;
        }
    }
    HashMap::new()
}

/// Resolve the active language code from `manifest.config["i18n"]`.
/// Returns `None` when the manifest is unreachable or the key is absent.
pub async fn resolve_active_lang(kubo_url: &str, root_cid: &str) -> Option<String> {
    let manifest: RuntimeManifest = kubo::dag_get(kubo_url, root_cid).await.ok()?;
    manifest
        .config
        .get("i18n")
        .and_then(|v| v.as_str())
        .map(String::from)
}

async fn load_all_messages(
    kubo_url: &str,
    lang_cid: Option<&str>,
    root_cid: Option<&str>,
) -> HashMap<String, HashMap<String, String>> {
    let mut all = bundled_messages();

    let lang_map = fetch_lang_map(kubo_url, lang_cid, root_cid).await;
    for (code, link) in &lang_map {
        if let Ok(bytes) = kubo::cat_bytes(kubo_url, &link.cid).await {
            if let Ok(ftl) = String::from_utf8(bytes) {
                all.insert(code.clone(), parse_ftl(&ftl, code));
            }
        }
    }

    all
}
